### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by ozanilbey** [phonetworks/gapp-build#7]
- [x] Remove "properties" section from main graph node
- [x] Simulate click on buttons when pressed enter
- [x] Add scrolling to left and right columns
- [x] Add additional style to selected nodes/edges to emphasize
- [x] Remove formative property from edges that are not 'Write'
- [x] Permissions table should be 4x4 table of checkboxes
- [x] Add id attribute as default to the first position and prevent editing/deleting/reordering ( id: ID )
- [x] Prevent nodes/edges having the same exact name
- [x] Enable adding edges by drawing from one node to another
- [x] Enable having multiple headed edges and simulate it on graph visualization
- [x] Prevent nodes/edges to have more than one attributes with the same name
- [ ] Add readme file inside the saved ZIP file
- [ ] Add readme file to repository
- [x] If location.href contains ?nobrand, navigation background color will be a generic color
- [x] Make creating edges drawing-only
- [ ] Enable Help mode using Tippys
- [x] Create Switch component
- [x] Make Navigation adapt to new system
- [x] Change sidebars to match the new system
- [x] Create "add" button from scratch
- [x] Check responsiveness after changes

**Comment by ozanilbey** [comment]
@esokullu Can you handle creating the readme text inside the saved ZIP file? It should clarify the next steps after creating pgql files.

**Comment by esokullu** [comment]
I would add 

- [x] something that shows zoom level in the bottom-right corner.

**Comment by ozanilbey** [comment]
I'll cover this soon (if vis.js supports zoom indicator, or at least provides data)

**Comment by ozanilbey** [comment]
There is an option in vis.js to set zoom amount. I can create something out of this but it needs to be re-rendered each time zoom changed. That means we will loose selected item every time the zoom option changes.

**Comment by ozanilbey** [comment]
Mostly done. Only readme files are left in the list. @esokullu
